Repository Freshly/malfunction, pull requests merged in 2020-01, with the labels that each got.

#10 Gem Updates
  Gemfile
  Gemfile.lock
  malfunction.gemspec
  spec/spec_helper.rb
Labels: Maintenance

#11 Release 0.1.1
  CHANGELOG.md
  Gemfile.lock
  lib/malfunction/version.rb
Labels: Release

#12 Release 0.1.1
  CHANGELOG.md
  Gemfile.lock
  README.md
  lib/malfunction.rb
  lib/malfunction/attribute_error.rb
  lib/malfunction/attribute_error_collection.rb
  lib/malfunction/malfunction/attribute_errors.rb
  lib/malfunction/malfunction/builder.rb
  lib/malfunction/malfunction/context.rb
  lib/malfunction/malfunction/core.rb
  lib/malfunction/malfunction_base.rb
  lib/malfunction/rspec/custom_matchers.rb
  lib/malfunction/rspec/custom_matchers/contextualize_as.rb
  lib/malfunction/rspec/custom_matchers/define_problem.rb
  lib/malfunction/rspec/custom_matchers/have_default_problem.rb
  lib/malfunction/rspec/custom_matchers/use_attribute_errors.rb
  lib/malfunction/spec_helper.rb
  lib/malfunction/version.rb
  malfunction.gemspec
  spec/malfunction/attribute_error_collection_spec.rb
  spec/malfunction/attribute_error_spec.rb
  spec/malfunction/malfunction/attribute_errors_spec.rb
  spec/malfunction/malfunction/builder_spec.rb
  spec/malfunction/malfunction/context_spec.rb
  spec/malfunction/malfunction/core_spec.rb
  spec/malfunction/malfunction_base_spec.rb
  spec/spec_helper.rb
  spec/support/shared_context/with_an_example_malfunction.rb
  spec/support/test_classes/chumble_malfunction.rb
  spec/support/test_classes/floob_malfunction.rb
  spec/support/test_classes/grodus_malfunction.rb
  spec/support/test_classes/grumbo_malfunction.rb
  spec/support/test_classes/plumbus_malfunction.rb
  spec/test_classes/chumble_malfunction_spec.rb
  spec/test_classes/floob_malfunction_spec.rb
  spec/test_classes/grodus_malfunction_spec.rb
  spec/test_classes/grumbo_malfunction_spec.rb
  spec/test_classes/plumbus_malfunction_spec.rb
Labels: Release

#13 allow rails > 5
  Gemfile.lock
  malfunction.gemspec
Labels: Correction

#15 Gem Update
  Gemfile.lock
  malfunction.gemspec
Labels: Correction, Maintenance

#16 Release 0.2.0
  CHANGELOG.md
  Gemfile.lock
  lib/malfunction/version.rb
  malfunction.gemspec
Labels: Release
